<div class="container max-w-4xl px-6">
	<h1>About Odin's Room</h1>
  <p class="mb-8 text-lg text-base-content">
		<span class="font-bold">Odin's Room</span> is a website created using <a href="https://kit.svelte.dev" class="font-bold" target="_blank">SvelteKit</a> that utilizes <a href="https://photos.google.com" class="font-bold" target="_blank">Google Photos</a>. I designed this website because I'm too busy, forgetful and easily distracted to keep up with sending all of the photos taken of my son by myself and his mother to our family by text or email... and as an aspiring web developer, I was excited by the challenge of coding a unique solution to improve my skills.
	</p>
	<h2>The Challenge:</h2>
	<p class="mb-8 text-base-content">
		Our son was born September 15th, 2022, and like most new parents we have been snapping photos of him constantly. Both of us have Google Photos accounts that automatically backup and index our photos and videos, and to make sharing these photos with each other easier, we created a shared album accessible from either account that we could both contribute photos of Odin to. This was convenient for us, but not so much for our family. It was tricky to keep up with who sent which photos to grandma, who sent which ones to grandpa, and weeks or months would go by with both of us forgetting to send photos to anyone; we didn't want to simply invite everyone to the shared album we had, and not everyone in our family has a Google account or knows how to use Google Photos.
	</p>
	<h2>The Solution:</h2>
	<p class="mb-8 text-base-content">
		Luckily, Google provides developers with plenty of tools for utilizing their services through APIs. Google Photos has a public REST API which allows authenticated users to fetch photos, though it is not an easy API to work with, and there are very few other examples I've found of other developers using it this way (in particular, accessing albums without requiring individual authentication for each user - rather, authenticating access using my own account and making that publically available, while preserving the authentication tokens without generating new sessions - I still have to manually generate new tokens every couple of days to make this thing work, which is a pain in the ass, but I'm working on a solution). I set up my own authentication to control access to the albums, as I only wish to share these photos with family members and close friends that I give permission, using <a href="https://supabase.com" class="font-bold" target="_blank">Supabase</a> - a remote Postgres SQL database with a basic email/password authentication provider, which I may also utilize to add a simple comment system to the photos. Still working on that part...
	</p>
	<h2>Form & Function</h2>
	<p class="mb-8 text-base-content">
		As I mentioned before, the site is built using <a href="https://kit.svelte.dev" class="font-bold" target="_blank">SvelteKit</a>, which has quickly become my favorite Javascript based meta-framework for web application development, which is of course a web framework for the <a href="https://svelte.dev" class="font-bold" target="_blank">Svelte</a> Javascript library. The developer experience working with Svelte is unmatched - everything is straight forward, intuitive, and ergonomic. This site utilizes a combination of server and client side rendering with SvelteKit, which makes this otherwise complex hybridization very easy. The site is hosted on <a href="https://vercel.com" class="font-bold" target="_blank">Vercel</a>, which is a serverless hosting platform that integrates seamlessly with SvelteKit, and is also free for personal projects. The site is styled using <a href="https://tailwindcss.com" class="font-bold" target="_blank">TailwindCSS</a> and <a href="https://daisyui.com" class="font-bold" target="_blank">DaisyUI</a>, the combination of which takes the heavy lifting out of styling and makes it easy to create a beautiful, responsive, and accessible user interface. And just to add a bit of cutting edge web tech to the mix, I made use of the new <a href="https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API">View Transitions API</a> to create the smooth transitions between the thumbnail and full size images in the album galleries. This is not supported on all browsers yet, but anything <a href="https://chrome.google.com" class="font-bold" target="_blank">Chromium</a> based (Chrome, Opera, Vivaldi, Edge, Brave, etc.) should work just fine.
	</p>
</div>